### ISSUE TITLE
Definir todos los casos de uso de un usuario normal

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#13]
A parte de crear pedidos de servicios y consultarlos, puede hacer algo mas? @pslencinas

**Comment by pslencinas** [comment]
Un usuario normal puede hacer lo siguiente:
- Pedir Servicios.
- Consultar por los servicios pedidos.
- Cuando tenga los servicios aprobados, puede pedir modificaciones sobre los mismos. Por ejemplo, si uno ya tiene una linea asignada con discado Local, puede pedir un cambio por discado Internacional. Esto todavia no te lo dije, despues te lo muestro.
