### ISSUE TITLE
Modificar comportamiento del popup Nuevo Servicio

### ISSUE THREAD

**Issue by pslencinas** [lucaslencinas/telefonia#15]
Cuando clickeas en Nuevo Servicio y no le das Cancelar o cerras la ventana, igual te abre la página para completar el formulario de Nuevo Servicio. Hay que modificar ese comportamiento.

**Comment by lucaslencinas-zz** [comment]
Ya lo arrregle pero no se porque hay una version vieja en https://telefonia.herokuapp.com/
Vos subiste algo ahi?
Ahora configure que cuando se haga un git push origin master, se sincronice automaticamente con heroku, asi no hay versiones distintas.

Pero todavia nose porque hay una version vieja levantada en la pagina... voy a seguir viendo

**Comment by lucaslencinas-zz** [comment]
Por lo que me di cuenta recien:
- Si vas a https://telefonia.herokuapp.com/ --> aparece la version vieja.
- Si vas a https://telefonia.herokuapp.com/index.html --> aparece la version nueva. Deberia ver porque pasa eso, aunque ya me paso algun momento lo mismo. No deberia ser asi

**Comment by pslencinas** [comment]
Eso lo podes ver en la configuración del Web Server, vos le podes decir que .html tiene que levantar por default. Seguro esta apuntando a otro lado, pero no se como lo maneja Heroku.

**Comment by lucaslencinas-zz** [comment]
Oka, me fijo
