### ISSUE TITLE
Servicios disponibles en paises

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#16]
@pslencinas 
Que servicios se pueden dar de alta en que paises y en que edificios?
O todos los servicios estan disponibles para todos lados?

**Comment by pslencinas** [comment]
Por ahora, todos los servicios estan disponibles para todos los paises/edificios. Lo que hay que tener en cuenta es que cuando seleccionan un país solo tiene que traer los edificios de ese pais.

**Comment by lucaslencinas-zz** [comment]
Si, eso ya lo arregle en el cambio que hice el finde
