### ISSUE TITLE
Campos de altaInterno

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#17]
@pslencinas  fijate si la fuente de los datos es la correcta en cada caso, y que pasa con los que no se.
## Alta Interno:
-  **idIBM** --> OK, del login
-  **nombre** --> OK, del login
-  **apellido** --> OK, del login
-  **ticket** --> OK, autoincremental
-  **servicio** --> Hace referencia al tipo de servicio solicitado (altainterno, altalineaanalogica..etc)
-  **nivelAprobacion** --> campo numérico (0-No requiere aprobación, 1-Requiere aprobación 1er Manager, 2- Requiere aprobación 2do Manager)
-  **tipo** --> ¿?
-  **pais**--> OK, del formulario
-  **fechaInicio** Es la actual del pedido
-  **estado** --> pendiente | rechazado | aprobado. Alguno mas?
-  **idFManager** --> me lo da el "Traer Datos"
-  **fManager** --> me lo da el "Traer Datos"
-  **idSManager** --> me lo da el "Traer Datos"
-  **sManager** --> me lo da el "Traer Datos"
-  **fechaFManager** --> Campo Fecha/Hora cuando el 1er Manager aprobó/rechazó la solicitud
-  **fechaSManager** --> Campo Fecha/Hora cuando el 2er Manager aprobó/rechazó la solicitud
-  **fechaTelefonia** --> Campo Fecha/Hora cuando el Administrador aprobó/rechazó la solicitud
-  **fechaCerrado** --> Campo Fecha/Hora cuando el Administrador aprobó/rechazó la solicitud
-  **edificio** --> OK
- **departamento** --> me lo da el "Traer Datos"
-  **piso** --> OK, del formulario
-  **intReferencia** --> OK, del formulario
-  **aparato** --> OK, del formulario
-  **voicemail** --> OK, del formulario
-  **discado** --> es el tipo de discado que selecciono, del formulario.
-  **justificacion** --> OK, del formulario
-  **interno** --> Este campo lo completa el administrador de Telefonia. Asigna un número de interno
-  **macAddress** -->  interno --> Este campo lo completa el administrador de Telefonia. Asigna un aparato físico detallado por su mac-address.
-  **marca** --> interno --> Este campo lo completa el administrador de Telefonia. Asigna Marca del teléfono
-  **modelo** --> interno --> Este campo lo completa el administrador de Telefonia. Asigna Marca del teléfono.
-  **serie** --> Idel anterior.
-  **motivoFManager** --> Si el Manager Rechazó la solicitud, le tiene que pedir un motivo. Este texto va aca.
-  **motivoSManager** --> Si el Manager Rechazó la solicitud, le tiene que pedir un motivo. Este texto va aca.
-  **motivoTelefonia** --> Si Telefonia Rechazó la solicitud, le tiene que pedir un motivo. Este texto va aca.

En el traer datos, tengo un "idLotusNote". Me sirve?

**Comment by lucaslencinas-zz** [comment]
Tengo anotado que en el peddo a IBM me devuelve un departamento, en esta tabla no esta. esta bien?

**Comment by pslencinas** [comment]
Respuestas:

```
servicio --> Hace referencia al tipo de servicio solicitado (altainterno, altalineaanalogica..etc)
nivelAprobacion --> campo numérico (0-No requiere aprobación, 1-Requiere aprobación 1er Manager, 2- Requiere aprobación 2do Manager)
tipo --> ¿?
estado --> pendiente | rechazado | aprobado. Alguno mas?
fechaFManager --> Campo Fecha/Hora cuando el 1er Manager aprobó/rechazó la solicitud
fechaSManager --> Campo Fecha/Hora cuando el 2do Manager aprobó/rechazó la solicitud
fechaTelefonia --> Campo Fecha/Hora cuando el Administrador aprobó/rechazó la solicitud
fechaCerrado --> Campo Fecha/Hora cuando el Administrador aprobó/rechazó la solicitud
discado --> es el tipo de discado que selecciono, del formulario.
interno --> Este campo lo completa el administrador de Telefonia. Asigna un número de interno
macAddress -->     interno --> Este campo lo completa el administrador de Telefonia. Asigna un aparato físico detallado por su mac-address.
marca -->     interno --> Este campo lo completa el administrador de Telefonia. Asigna Marca del teléfono
modelo -->     interno --> Este campo lo completa el administrador de Telefonia. Asigna Marca del teléfono.
serie --> Idel anterior.
motivoFManager --> Si el Manager Rechazó la solicitud, le tiene que pedir un motivo. Este texto va aca.
motivoSManager --> Si el Manager Rechazó la solicitud, le tiene que pedir un motivo. Este texto va aca.
motivoTelefonia --> Si Telefonia Rechazó la solicitud, le tiene que pedir un motivo. Este texto va aca.
```

En el traer datos, tengo un "idLotusNote". Me sirve? -> Creo que esto era lo mismo que el ID numero de empleado, no me acuerdo ahora.

Agrega el campo Departamento en la Tabla.
