### ISSUE TITLE
Click en Servicios Pendientes

### ISSUE THREAD

**Issue by pslencinas** [lucaslencinas/telefonia#18]
*_@lucaslencinas *_
Cuando haces click en Servicios Pendientes, la descripción en la página dice: Servicios Esperando Confirmación. Yo modifiqué esto pero no me funcionó. Fijate de tocarlo.

**Comment by lucaslencinas-zz** [comment]
Listo con el commit 6ca9b5206262676dbdcb7c8c8207bc460ce35ff1
