### ISSUE TITLE
Info adicional del ticket

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#27]
Pensar en como se muestra la info adicional del ticket. Hay un log de cambios respecto al mismo? como se guarda en la base eso?
@pslencinas como seria esto? Se muestra algun tipo de historial sobre un ticket?
Algo como:
4 de marzo --> Creacion de ticket
14 de marzo --> Pendiente de Gerente1
27 de marzo --> Pendiente de Telefonia
4 de abril --> Aprobado
El usuario ve esto, o solo el estado actual del ticket y listo?

**Comment by pslencinas** [comment]
Si, se tiene que ver el log de la actividad, algo parecido como lo pones. Te adjunto como se hoy. No se como esta armado eso hoy, pero podríamos utilizar una tabla aparte solo de Logs por cada actividad referenciandolos por el número de ticket y solicitud.

![log de actividad](https://cloud.githubusercontent.com/assets/14349696/15194793/264ff1da-179b-11e6-8842-55c158ce4671.jpg)
