### ISSUE TITLE
con que seguir

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#28]
- ~~traer los tickets de un usuario~~
- traer los tickets de un usuario manager
- traer los tickets de los usuarios que responden a un manager.
- ~~agregar los campos nuevos en la table de ibm_data~~
- ~~agregar estado pendienteTelefoniaLocal y telefoniaAdmin. Se usa solo para altaInterno. El resto va a telefoniaAdmin~~
- El gerente solo aprueba o rechaza. Podria modificar los campos que quisiese de ser necesario.
- TelefoniaLocal agrega mac, marca, serie, modelo
- Telefonia Admin agrega interno
- ~~Nivel de aprobacion, 0(no requiere, por ejemplo reseteo pass), 1(appr gerente1) ,2(appr gerente2)~~
- ~~fManager y sManager son nombres completos, entonces en la tabla usuarios debe ser nombre completo.~~
- Crear tabla TelefoniaAdmin para saber quienes son admins con (rol, id,fullname,pais,mail, bla)
- Si es TelAdmin, ve todo, no hay filtro de algun tipo. Peeero si es TelLocal ve los tickets que sean de su pais nada mas.
- ~~Crear tabla de logs con (ticket, tipodeServicio, idIBm, fullname, descripcion)~~

**Comment by lucaslencinas-zz** [comment]
@pslencinas me parece que no hace falta la tabla **"TelefoniaAdmin"** (que era para saber quienes eran admins de telefonia locales o totales) porque en la tabla empleados mia, tengo estos datos:

**idIBM**
**fullName**
isManager
**mail**
departamento
idFManager
fManager
idSManager
sManager
**rol**
**pais**
y con eso me parece que alcanza. Hago un select del idIBM que se loguea y veo si es admin local o total con el campo **"rol"**

**Comment by pslencinas** [comment]
De todas formas hay que usar un tabla para cargar perfiles de admin porque esta es local. Podes usar la que tenes para no andar duplicando tablas.
