### ISSUE TITLE
Contenido de la Barra superior

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#5]
![seleccion_027](https://cloud.githubusercontent.com/assets/1664768/14581500/28b3489e-03c5-11e6-9d6a-c10a362d6452.png)
Esas opciones estan para todos los tipos de usuarios?
Cuando puedas especificame que aparece en cada caso o eso lo decido yo?
Por ejemplo ahi aparece nuevo Servicio, pero no aparece nueva Solicitud. En la barra del costado tampoco:
![seleccion_028](https://cloud.githubusercontent.com/assets/1664768/14581503/59febf6e-03c5-11e6-921f-87a97aaf0fd8.png)

Cual seria la diferencia entre uno y el otro?
@pslencinas.
PD: Si contestas directamente el mail que te llega, con lo que escribiste se crea un comentario en este issue de github automaticamente.

**Comment by pslencinas** [comment]
Cuando clickeas Nuevo Servicio te sale la opcion que te pase por mail, un
popup donde seleccionas el pais y despues el servicio que necesitas
(interno extension, pickup....etc). Las opciones de nuevo perfil y acciones
dejalo para los admin, despues te paso esas opciones.
Solicitud o servicio es lo mismo, no recuerdo si yo lo habia llamado asi
por algo, pero dejalo como servicio, despues vemos
