### ISSUE TITLE
acomodar la barra lateral

### ISSUE THREAD

**Issue by lucaslencinas-zz** [lucaslencinas/telefonia#6]
![seleccion_028](https://cloud.githubusercontent.com/assets/1664768/14588306/6791e6f6-049c-11e6-82af-f526bd9835a1.png)

Que al clickear ahi, solo muestre el resultado de esas solicitudes y no ejecute la accion de crear.
Solo Solicitudes de Servicios, no hay division.
tal vez No haga falta mostrar toda esa division especifica ahi --> Se podria hacer un filtro de Aprobadas, Rechazadas, Esperando confirmacion nada mas para los usuarios normales.

**Comment by pslencinas** [comment]
Es que esa vista es solo para ver solicitudes(activas o pendientes), no
para crearlas. Para pedir una nueva solicitud hay que clickear en el icono
de la barra horizontal que dice nuevo servicio.
